### ISSUE TITLE
Module does not exist in the node_modules folder

### ISSUE THREAD

**Issue by Jarrio** [tokomlabs/haxe-react-addons#16]
I am attempting to use this and it doesn't seem to work for me. I am receiving the following error:

`(node:3452) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): UnableToResolveError: Unable to resolve module material-ui/lib/slider from W:\Haxe\HaxeReact\Budget\bin\index.android.js: Module does not exist in the module map or in these directories:
  W:\Haxe\HaxeReact\Budget\bin\node_modules\material-ui\lib` 

and sure enough the folder does not exist at that location. I have tried cleaning the cache, removing the node_modules folder and rebuilding and also resetting the packager cache.

Am I missing something obvious? I have the basic sample project located [here](https://github.com/haxe-react/haxe-react-native-sample) and I have removed  the `.haxelib` and `haxelib` folders so that it grabs the installs straight from my default install location. 

Another thing to mention is that the import for the modules all run fine, vscode is able to correctly identify the `addon` package and provide auto-completion for imported libs.

**Comment by elsassph** [comment]
You need to `npm install` the modules.

**Comment by Jarrio** [comment]
Sorry I'm completely new to the npm/node side of things and I'm actually just a haxe user. I ran `npm install material-ui` and it installed the files in the `node_modules` folder but it still results in the same error message.

I'm wondering if I have installed the right material-ui library as the one which is given from the above command results in a *very* different folder structure than the one attempted to be found

**Comment by elsassph** [comment]
You may be missing other dependencies.

Normally you want to create a `package.json` file to manage your npm dependencies - there's good doc about that.

Also you should describe your build process.

**Comment by elsassph** [comment]
Also you seem to be trying react-native: I suggest you look at this quickstart project: https://github.com/haxe-react/haxe-react-native-sample

**Comment by Jarrio** [comment]
I mentioned that is the project I am starting from in my original post, I did link to it as well. The basic project works fine. It is only when I try to introduce this `haxe-react-addons` that things stop working, for example doing `import react.native.component.Slider;` works fine but doing `import react.addon.materialui.Slider;` compiles fine in haxe but then errors on my phone due to there not being a matching material-ui folder in the `bin/node_modules` path

**Comment by kevinresol** [comment]
You need to use `npm install` to make the `material-ui` exist in where it should be.
Btw, I think that the material-ui library is for React and _not_ React Native. So your effort done for this thread will very likely be wasted at the end anyway.

**Comment by Jarrio** [comment]
Oh, my apologies! I didn't realise this wasn't for react-native.

**Comment by zabojad** [comment]
Hi there ! Apologies for answering so late and thank you @elsassph  and @kevinresol for answering this. @Jarrio `haxe-react-addons` is only a set of externs and/or haxe react (js) components to be used with `haxe-react` and to target javascript only (React JS). I'll push a better README soon to avoid any confusions about that.
